In [19]:
# Dependencies and Setup
import pandas as pd
import os
import csv

# File to Load
dataset_one = "../raw_datasets/book1-100k.csv"
dataset_two = "../raw_datasets/books100k-200k.csv"
dataset_three = "../raw_datasets/book200k-300k.csv"
dataset_four = "../raw_datasets/book300k-400k.csv"
dataset_five = "../raw_datasets/book400k-500k.csv"
dataset_six = "../raw_datasets/book500k-600k.csv"
dataset_seven = "../raw_datasets/book600k-700k.csv"
dataset_eight = "../raw_datasets/book700k-800k.csv"
dataset_nine = "../raw_datasets/book800k-900k.csv"
dataset_ten = "../raw_datasets/book900k-1000k.csv"

In [42]:
#Read book dataset file and store into Pandas DataFrames
dataset_one_r = pd.read_csv(dataset_one)
dataset_two_r = pd.read_csv(dataset_two)
dataset_three_r = pd.read_csv(dataset_three)
dataset_four_r = pd.read_csv(dataset_four)
dataset_five_r = pd.read_csv(dataset_five)
dataset_six_r = pd.read_csv(dataset_six)
dataset_seven_r = pd.read_csv(dataset_seven)
dataset_eight_r = pd.read_csv(dataset_eight)
dataset_nine_r = pd.read_csv(dataset_nine)
dataset_ten_r = pd.read_csv(dataset_ten)

In [53]:
combined_file=dataset_one_r.append([dataset_two_r, dataset_three_r, dataset_four_r, dataset_five_r, dataset_six_r,\
                      dataset_seven_r, dataset_eight_r, dataset_nine_r, dataset_ten_r])

In [59]:
combined_file.head(10)

,Id,Name,RatingDist1,pagesNumber,RatingDist4,RatingDistTotal,PublishMonth,PublishDay,Publisher,CountsOfReview,PublishYear,Language,Authors,Rating,RatingDist2,RatingDist5,ISBN,RatingDist3,Description,Count of text reviews
0,1,Harry Potter and the Half-Blood Prince (Harry ...,1:9896,652,4:556485,total:2298124,16,9,Scholastic Inc.,28062,2006,eng,J.K. Rowling,4.57,2:25317,5:1546466,NaN,3:159960,NaN,NaN
1,2,Harry Potter and the Order of the Phoenix (Har...,1:12455,870,4:604283,total:2358637,1,9,Scholastic Inc.,29770,2004,eng,J.K. Rowling,4.50,2:37005,5:1493113,0439358078,3:211781,NaN,NaN
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,1:108202,309,4:1513191,total:6587388,1,11,Scholastic Inc,75911,2003,eng,J.K. Rowling,4.47,2:130310,5:4268227,NaN,3:567458,NaN,NaN
3,4,Harry Potter and the Chamber of Secrets (Harry...,1:11896,352,4:706082,total:2560657,1,11,Scholastic,244,2003,eng,J.K. Rowling,4.42,2:49353,5:1504505,0439554896,3:288821,NaN,NaN
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,1:10128,435,4:630534,total:2610317,1,5,Scholastic Inc.,37093,2004,eng,J.K. Rowling,4.57,2:24849,5:1749958,043965548X,3:194848,NaN,NaN
5,6,Harry Potter and the Goblet of Fire (Harry Pot...,1:9419,734,4:606800,total:2431085,28,9,Scholastic,31978,2002,eng,J.K. Rowling,4.56,2:24282,5:1612165,NaN,3:178419,NaN,NaN
6,8,"Harry Potter Boxed Set, Books 1-5 (Harry Potte...",1:402,2690,4:4650,total:43968,13,9,Scholastic,166,2004,eng,J.K. Rowling,4.78,2:283,5:37432,0439682584,3:1201,NaN,NaN
7,9,"Unauthorized Harry Potter Book Seven News: ""Ha...",1:0,152,4:7,total:28,26,4,Nimble Books,1,2005,en-US,W. Frederick Zimmerman,3.79,2:5,5:10,0976540606,3:6,NaN,NaN
8,10,"Harry Potter Collection (Harry Potter, #1-6)",1:257,3342,4:4358,total:30313,12,9,Scholastic,809,2005,eng,J.K. Rowling,4.73,2:218,5:24406,0439827604,3:1074,NaN,NaN
9,12,The Ultimate Hitchhiker's Guide: Five Complete...,1:3443,815,4:75683,total:274268,1,11,Gramercy Books,255,2005,eng,Douglas Adams,4.37,2:7613,5:157499,0517226952,3:30030,NaN,NaN

In [54]:
# Authors, Name, ISBN, ID, Rating
master_df =combined_file

In [55]:
master_df[["Authors", "Name", "ISBN", "Rating"]]

,Authors,Name,ISBN,Rating
0,J.K. Rowling,Harry Potter and the Half-Blood Prince (Harry ...,NaN,4.57
1,J.K. Rowling,Harry Potter and the Order of the Phoenix (Har...,0439358078,4.50
2,J.K. Rowling,Harry Potter and the Sorcerer's Stone (Harry P...,NaN,4.47
3,J.K. Rowling,Harry Potter and the Chamber of Secrets (Harry...,0439554896,4.42
4,J.K. Rowling,Harry Potter and the Prisoner of Azkaban (Harr...,043965548X,4.57
...,...,...,...,...
40885,Janet Holmes,Gendered Talk at Work: Constructing Gender Ide...,1405117591,4.28
40886,Jack Kammer,Good Will Toward Men: Women Talk Candidly abou...,0312104715,0.00
40887,Randy Horn,Would You Rather . . . ?: The Outrageous Book ...,0761124209,3.81
40888,Kathryn Graham,Addictions Treatment for Older Adults: Evaluat...,1560248572,0.00
40889,Kathryn T.S. Bass,Within/Without,097495974X,5.00

In [56]:
compression_opts = dict(method='zip',
                       archive_name='master_book.csv')

master_df.to_csv('master_book.zip', index=False,
                compression=compression_opts)